### ISSUE TITLE
Support new React Native new architecture (TurboModules/Fabric)

### ISSUE THREAD

**Issue by tom-sherman** [react-native-share/react-native-share#1232]
See https://reactnative.dev/docs/new-architecture-library-intro

https://reactnative.dev/blog/2022/06/16/resources-migrating-your-react-native-library-to-the-new-architecture

**Comment by mikehardy** [comment]
PRs are always welcome :pray:

**Comment by MateusAndrade** [comment]
Hi @tom-sherman, did you have a chance to test with the newest arch? As far as I remember, most of the libraries should be compatible with that. 🤔

**Comment by mikehardy** [comment]
@MateusAndrade it's not about compatible as in "it still works" it's supporting it as in "the JS/native connection is no longer through the JSI but through codegen etc - check out:

https://reactnative.dev/docs/new-architecture-intro

Section "Supporting the New Architecture in your Library"

**Comment by MateusAndrade** [comment]
> Section "Supporting the New Architecture in your Library"

Nice!!! I caused confusion here, sorry for that. I will read about it, but this looks like a release that should be a major one @mikehardy ?

**Comment by mikehardy** [comment]
For sure a major release because at minimum the module will require the NDK and probably a new minimum react-native version of 0.68 (since that was the first time new arch was publicly available). I haven't done a conversion yet so I'm not sure how long the process takes per module

**Comment by MateusAndrade** [comment]
> For sure a major release because at minimum the module will require the NDK and probably a new minimum react-native version of 0.68 (since that was the first time new arch was publicly available). I haven't done a conversion yet so I'm not sure how long the process takes per module

I think I need to read more about the new arch before thinking about it, But as far as I remember, a good alternative would be creating a library from scratch in order to test/understand everything.

Do you know any OS projects that had been migrated to the new arch?

**Comment by mikehardy** [comment]
swmansion appears to be the vanguard here with reanimated, gesture-handler and screens all working through it - https://blog.swmansion.com/announcing-reanimated-3-16167428c5f7

https://github.com/software-mansion/react-native-reanimated/pulls?q=is%3Apr+fabric
https://github.com/software-mansion/react-native-screens/pulls?q=is%3Apr+fabric

etc :-)

**Comment by tom-sherman** [comment]
There is also https://github.com/react-native-community/RNNewArchitectureLibraries to act as a demo

**Comment by AliHaidar110** [comment]
any progress on supporting the new architecture? I think I might give it a shot if no one is working on it.

PS: my first time working on something like that, hopefully, I will be able to do it. :)

**Comment by MateusAndrade** [comment]
> any progress on supporting the new architecture? I think I might give it a shot if no one is working on it.
> 
> PS: my first time working on something like that, hopefully, I will be able to do it. :)

Not now, but I would love to help you. Let me know if you need anything. 😄

**Comment by Yasas4D** [comment]
Any progress on this?

**Comment by zabojad** [comment]
Hi there, is there any ongoing PR for that on which we could give you a hand?

**Comment by zabojad** [comment]
Here is my PR: https://github.com/react-native-share/react-native-share/pull/1402

It works on my side...

**Comment by MateusAndrade** [comment]
Fixed with https://github.com/react-native-share/react-native-share/pull/1402!

**Comment by timothyerwin** [comment]
has this been released yet? I'm on the latest but I'm still getting this error after deployment with new arch and fabric

```
In file included from /node_modules/react-native-share/ios/RNShare.mm:2:
/node_modules/react-native-share/ios/RNShare.h:12:9: fatal error: 'React-Codegen/RNShareSpec/RNShareSpec.h' file not found
#import <React-Codegen/RNShareSpec/RNShareSpec.h>
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

**Comment by MateusAndrade** [comment]
> has this been released yet? I'm on the latest but I'm still getting this error after deployment with new arch and fabric
> 
> ```
> In file included from /node_modules/react-native-share/ios/RNShare.mm:2:
> /node_modules/react-native-share/ios/RNShare.h:12:9: fatal error: 'React-Codegen/RNShareSpec/RNShareSpec.h' file not found
> #import <React-Codegen/RNShareSpec/RNShareSpec.h>
>         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 1 error generated.
> ```

I think this was fixed with https://github.com/react-native-community/react-native-share/compare/v9.0.1. Which version are you using?

**Comment by GuillaumeHemmen** [comment]
I also have the exact same issue as described by @timothyerwin . I am using version 9.4.1

**Comment by joseAlvarezTenpo** [comment]
i have the same issue in RN 0.72.4

**Comment by devic021** [comment]
> has this been released yet? I'm on the latest but I'm still getting this error after deployment with new arch and fabric
> 
> ```
> In file included from /node_modules/react-native-share/ios/RNShare.mm:2:
> /node_modules/react-native-share/ios/RNShare.h:12:9: fatal error: 'React-Codegen/RNShareSpec/RNShareSpec.h' file not found
> #import <React-Codegen/RNShareSpec/RNShareSpec.h>
>         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 1 error generated.
> ```

Yeah, same here with 9.4.1 version and new architecture...

**Comment by alexanderoskin** [comment]
Same here with 10.0.1 version and new architecture

**Comment by zhenkaGo** [comment]
I've made PR to fix this [1490](https://github.com/react-native-share/react-native-share/pull/1490)

while the PR is being checked, you can use the patch.
```
diff --git a/node_modules/react-native-share/ios/RNShare.h b/node_modules/react-native-share/ios/RNShare.h
index 668fd8e..3ec51db 100644
--- a/node_modules/react-native-share/ios/RNShare.h
+++ b/node_modules/react-native-share/ios/RNShare.h
@@ -9,7 +9,7 @@
 #endif
 
 #if RCT_NEW_ARCH_ENABLED
-#import <React-Codegen/RNShareSpec/RNShareSpec.h>
+#import <RNShareSpec/RNShareSpec.h>
 #endif
 
 @interface RNShare : NSObject <RCTBridgeModule, UIDocumentPickerDelegate>
```

**Comment by hengkx** [comment]
Any progress on this?

**Comment by jslok** [comment]
> Any progress on this?

I haven't tried it but the latest version includes the fix.

**Comment by Sowed** [comment]
> > Any progress on this?
> 
> I haven't tried it but the latest version includes the fix.

Still getting this error with RN 0.72.9 and RNshare 10.0.2 even when it's already got @zhenkaGo's fix
